from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT_PATH = ROOT / "Project_Horizon_Continuous_State_QVI_ASCII_Visual.md"


def render_true_tree_table(step_labels: list[str]) -> str:
    headers = ["state"] + step_labels
    max_state = len(step_labels) - 1
    rows: list[list[str]] = []
    for state in range(max_state, -1, -1):
        row = [f"state {state}"]
        for step in range(len(step_labels)):
            row.append("o" if state <= step else "")
        rows.append(row)
    table = make_table(headers, rows)
    caption = [
        "time -------------------------------------------------------------->",
        "",
        "Read by column:",
        "- t0 has 1 node",
        "- t1 has 2 vertical nodes",
        "- t2 has 3 vertical nodes",
        "- t3 has 4 vertical nodes",
    ]
    return "\n".join(caption + ["", table])


def make_table(headers: list[str], rows: list[list[str]]) -> str:
    widths = [len(header) for header in headers]
    for row in rows:
        for idx, cell in enumerate(row):
            widths[idx] = max(widths[idx], len(cell))

    def border() -> str:
        return "+-" + "-+-".join("-" * width for width in widths) + "-+"

    def render_row(row: list[str]) -> str:
        return "| " + " | ".join(cell.ljust(widths[idx]) for idx, cell in enumerate(row)) + " |"

    lines = [border(), render_row(headers), border()]
    lines.extend(render_row(row) for row in rows)
    lines.append(border())
    return "\n".join(lines)


def render_qvi_grid() -> str:
    headers = ["price", "day0", "day1", "day2", "day3", "day4", "day5"]
    prices = ["112", "109", "106", "103", "100", "97"]
    rows = [[price, "o", "o", "o", "o", "o", "o"] for price in prices]
    return make_table(headers, rows)


def render_transition_table() -> str:
    headers = ["price", "day t", "day t+1 neighborhood"]
    rows = [
        ["112", "", "o"],
        ["109", "", "o o o"],
        ["106", "X", "o o o o o"],
        ["103", "", "o o o"],
        ["100", "", "o"],
    ]
    return make_table(headers, rows)


def render_action_table() -> str:
    headers = ["Olympus action from q = 25.00%", "Residual Titan stake"]
    rows = [
        ["wait", "25.00%"],
        ["call 5.00%", "20.00%"],
        ["call 5.25%", "19.75%"],
        ["call 5.50%", "19.50%"],
        ["call 5.75%", "19.25%"],
        ["...", "..."],
        ["call 17.75%", "7.25%"],
        ["call 18.00%", "7.00%"],
        ["call 25.00%", "0.00%"],
    ]
    return make_table(headers, rows)


def build_markdown() -> str:
    tree = render_true_tree_table(["t0", "t1", "t2", "t3"])
    grid = render_qvi_grid()
    transition = render_transition_table()
    actions = render_action_table()

    return f"""# Project Horizon - Continuous State QVI ASCII Visual

Generated by `generate_qvi_ascii_visual.py`.

## Purpose

This note is a simplified visual aid for explaining the continuous-state QVI workstream.

The key distinction is:

- a true **tree** has one node at `t0` and fans outward as time moves to the right; and
- the QVI solver is better visualized as a **time-by-price grid** with a strategic decision problem at each grid point.

---

## 1. True Tree Shape

If you want a literal tree picture, this is the right shape.

```text
{tree}
```

That is the correct mental picture for a branching lattice.

---

## 2. QVI Time-By-Price Grid

The QVI solver is not a single fanning tree. Time is horizontal and price is vertical.

```text
{grid}
```

Each cell is one state point on the grid at which the solver can evaluate value.

---

## 3. One-Step Transition Intuition

For one current grid point, the next-day continuation value comes from a distribution of nearby next-day price states.

```text
{transition}
```

`X` is the current point whose continuation value is being computed.

---

## 4. What Lives At Each Grid Point

Each point is not just price and time. It is:

```text
Value(day t, stock price S, remaining Titan stake q)
```

So one grid point really means:

```text
(day, stock price, remaining Titan stake)
```

---

## 5. Fine Partial-Exercise Ladder

From `q = 25.00%`, Olympus compares a fine menu of admissible call sizes rather than a few coarse jumps.

```text
{actions}
```

So the 5% minimum tranche is still respected, but the residual stake is represented on a much finer ladder.

---

## 6. Overlap Node Logic

At each relevant point, the solver compares:

```text
WAIT
CALL some admissible amount
PUT the residual stake if Titan's right is live
```

In the overlap period, the value is the result of a strategic max/min step at that grid point.

---

## 7. Practical Reading Guide

If you are explaining this in a meeting, the cleanest sequence is:

1. Show the tree first so people see the usual branching intuition.
2. Then say: the QVI method is not that picture; it is a dense grid over time and price.
3. Then show the action ladder to explain that partial exercise is solved on a fine 0.25% control grid.

That is the cleanest honest ASCII representation of what the QVI solver is doing.
"""


def main() -> None:
    OUTPUT_PATH.write_text(build_markdown(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()